apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
