apiVersion: v1
kind: Secret
metadata:
  name: argo-helm-repo-istio
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: istio
  url: https://istio-release.storage.googleapis.com/charts
  type: helm
