apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  config:
    istio:
      local-gateway.istio-ingress.knative-local-gateway: "knative-local-gateway.istio-ingress.svc.cluster.local"